Client {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    keyTab="/etc/security/keytabs/client.keytab"
    storeKey=true
    doNotPrompt=true
    principal="client@EXAMPLE.COM";
};

Server {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    keyTab="/etc/security/keytabs/server.keytab"
    storeKey=true
    doNotPrompt=true
    principal="service/localhost@EXAMPLE.COM";
};
